config/routes.rb
Rails.application.routes.draw do
   resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	self.columns_hash['available_at'] = OpenStruct.new(type: :datetime, class: DateTime)
	 validates :name, :uniqueness => true, :presence => true
	 validates :time_start, :uniqueness => true, :presence => true
	 validates :time_end, :uniqueness => true, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
    @weekdays = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]
    # byebug
  end


  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
  	
 	# ev_params = params[:event]
	# @time_start = Time.zone.local(*ev_params.select {|k,v| k.to_s.index('time_start(') == 0 }.sort.map {|p| p[1].to_i})
	# @time_end = Time.zone.local(*ev_params.select {|k,v| k.to_s.index('time_end(') == 0 }.sort.map {|p| p[1].to_i})
    @event = Event.new(event_params)
	if @event.valid?
      	@event.save
      	# add a flash notice eventually
      	redirect_to events_path
    else
    	# add a flash notice eventually
        redirect_to new_event_path
    end
  end

  def edit
  	@event = Event.find(params[:id])
  end


  def update
  	@event = Event.find(params[:id])
  	@event.update(event_params)
  	flash[:notice] = 'Event was successfully updated.'
  	redirect_to event_path(@event)
  end

  def destroy
  	@event = Event.find(params[:id])
    @event.destroy
    flash[:notice] = 'Event was successfully destroyed.'
    redirect_to events_path
  end

  private

    def event_params
      params.require(:event).permit(:name, :time_start, :time_end)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/views/events/edit.html.slim
html
  head
  body
  p
  = form_for @event, method: :patch do |f|
      = f.label :event_name
      = f.text_field :name
      = f.label :event_time_start
      = f.datetime_select(:time_start, :include_seconds => true)
      = f.label :event_time_end
      = f.datetime_select(:time_end, :include_seconds => true)
      = f.submit

app/views/events/index.html.slim
doctype html
html
  head
    title My Calendar
    meta name="keywords" content="template language"

		body 
		 	- start_date = params.fetch(:start_date, Date.today).to_date
			- date_range = (start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week).to_a
			
			
			p
				= link_to "Last Month", start_date: date_range.first - 1.day
			p
				= link_to "Next Month", start_date: date_range.last + 1.day
			p
				= link_to "This Month", start_date: date_range.first.day

	    h1 My Events

	    table
	    	thead
	    		tr
	    		- @weekdays.each do |weekday|
		  			th = weekday

				tbody
					- date_range.each_slice(7) do |week|
						tr 
						  - week.each do | day |

								- day_events = @events.collect do |ev| 
									- puts day
									- ev.time_start.to_s.slice(0,10) == day

								td = day_events
						
								
							
									
									
	    
	    = link_to 'Create a new Event', new_event_path

	   
	    - @events.each do |event|
	    	= link_to event.name, event_path(event)



					

app/views/events/new.html.slim
html
  head
  body
  p
  = form_for @event, method: :post do |f|
      = f.label :event_name
      = f.text_field :name
      = f.label :event_time_start
      = f.datetime_select(:time_start, :include_seconds => true)
      = f.label :event_time_end
      = f.datetime_select(:time_end, :include_seconds => true)
      = f.submit

app/views/events/show.html.slim
doctype html
html
  head
  body
  	= link_to 'Back to Calendar', events_path
    h1 Event: #{@event.name}
    h2 #{@event.time_start.strftime("%A, %b %d %l:%M %p")} - #{@event.time_end.strftime("%A, %b %d %l:%M %p")}
    = link_to 'Edit Event', edit_event_path(@event)
    = link_to 'Delete Event', event_path(@event),  method: :delete, remote: true
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>